### ISSUE TITLE
New domain marzeniehakera.pl 

### ISSUE THREAD

**Issue by sptq** [Tracerneo/marzeniehakera#3]
Hi,

I just buy the domain marzeniehakera.pl. We can connect it with GitHub pages.

**Comment by Tracerneo** [comment]
Sounds good to me. You need to point marzeniehakera.pl to 192.30.252.153 and 192.30.252.154 with an A record and add a CNAME record pointing to tracerneo.github.io (I think).
https://help.github.com/articles/tips-for-configuring-an-a-record-with-your-dns-provider/

Once it's setup correctly on the DNS end, I will be able to configure it in the repo.

**Comment by sptq** [comment]
DNS setup are done.

**Comment by Tracerneo** [comment]
http://marzeniehakera.pl/
Works like a charm. Many thanks for the domain!

**Comment by Tracerneo** [comment]
DNS is not yet propagated properly (should be in less than an hour from now, when old records hit TTL).
Until then, http://tracerneo.github.io/marzeniehakera/ should be used.
